<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>CRUD History</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<?php echo base_url('superadmin') ?>">Home</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>CRUD History</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Generated CRUD List</h5>
                    <div class="ibox-tools">
                        <a href="<?php echo site_url('CrudGenerator') ?>" class="btn btn-primary btn-sm">
                            <i class="fa fa-plus"></i> Generate New CRUD
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <?php echo $this->session->flashdata('message'); ?>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="5%">No</th>
                                    <th width="15%">Table Name</th>
                                    <th width="15%">Controller</th>
                                    <th width="15%">Model</th>
                                    <th width="10%">Notification</th>
                                    <th width="12%">Generated Date</th>
                                    <th width="12%">Generated By</th>
                                    <th width="26%">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $no = 1;
                                foreach ($crud_history as $row): 
                                ?>
                                <tr>
                                    <td><?php echo $no++; ?></td>
                                    <td><strong><?php echo $row->table_name; ?></strong></td>
                                    <td><code><?php echo $row->controller_name; ?></code></td>
                                    <td><code><?php echo $row->model_name; ?></code></td>
                                    <td>
                                        <?php 
                                        $badge_class = 'badge-primary';
                                        if($row->notification_type == 'sweetalert') $badge_class = 'badge-success';
                                        if($row->notification_type == 'izitoast') $badge_class = 'badge-info';
                                        ?>
                                        <span class="badge <?php echo $badge_class; ?>"><?php echo ucfirst($row->notification_type); ?></span>
                                    </td>
                                    <td><?php echo date('d M Y H:i', strtotime($row->generated_at)); ?></td>
                                    <td><?php echo $row->generated_by_name; ?></td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="<?php echo site_url('CrudGenerator/edit/'.$row->id); ?>" class="btn btn-primary btn-xs" title="Edit/Regenerate">
                                                <i class="fa fa-pencil"></i> Edit
                                            </a>
                                            <a href="<?php echo site_url($row->controller_name); ?>" class="btn btn-info btn-xs" title="View CRUD">
                                                <i class="fa fa-eye"></i> View
                                            </a>
                                            <button type="button" class="btn btn-success btn-xs" onclick="openFile('<?php echo str_replace('\\', '\\\\', $row->view_directory . DIRECTORY_SEPARATOR . 'list.php'); ?>')" title="Edit List View">
                                                <i class="fa fa-list"></i> List
                                            </button>
                                            <button type="button" class="btn btn-warning btn-xs" onclick="openFile('<?php echo str_replace('\\', '\\\\', $row->view_directory . DIRECTORY_SEPARATOR . 'form.php'); ?>')" title="Edit Form View">
                                                <i class="fa fa-edit"></i> Form
                                            </button>
                                            <button type="button" class="btn btn-primary btn-xs" onclick="showDetails(<?php echo $row->id; ?>)" title="View Details">
                                                <i class="fa fa-info-circle"></i>
                                            </button>
                                            <a href="javascript:void(0);" onclick="deleteHistory('<?php echo site_url('CrudGenerator/delete_crud_history/'.$row->id) ?>')" class="btn btn-danger btn-xs" title="Delete History">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php if(empty($crud_history)): ?>
                                <tr>
                                    <td colspan="8" class="text-center">
                                        <p class="text-muted">No CRUD generated yet. <a href="<?php echo site_url('CrudGenerator') ?>">Generate your first CRUD</a></p>
                                    </td>
                                </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Details Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">CRUD Details</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="detailsContent">
                <p class="text-center"><i class="fa fa-spinner fa-spin"></i> Loading...</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<style>
    /* Force pagination and info to the left */
    .dataTables_wrapper .row:last-child {
        justify-content: flex-start !important;
    }
    .dataTables_wrapper .dataTables_info,
    .dataTables_wrapper .dataTables_paginate {
        float: left !important;
        text-align: left !important;
        justify-content: flex-start !important;
    }
    .dataTables_wrapper .dataTables_paginate ul.pagination {
        justify-content: flex-start !important;
        margin-top: 5px !important;
    }
    .dataTables_wrapper .dataTables_info {
        padding-top: 12px !important;
        margin-right: 20px !important;
    }
</style>

<script>
// Wait for jQuery to be available
(function checkJQuery() {
    if (typeof jQuery !== 'undefined') {
        initHistoryPage();
    } else {
        setTimeout(checkJQuery, 50);
    }
})();

function initHistoryPage() {
    $(document).ready(function(){
        $('.dataTables-history').DataTable({
            pageLength: 25,
            responsive: true,
            order: [[5, 'desc']] // Sort by date descending (Generated Date is index 5)
        });
    });
}

function openFile(filepath) {
    // Show file path info to user
    Swal.fire({
        title: 'File Location',
        html: '<p>File path:</p><code>' + filepath + '</code><br><br><p class="text-muted">Open this file in your code editor to make changes.</p>',
        icon: 'info',
        confirmButtonText: 'OK'
    });
}

function showDetails(id) {
    $('#detailsModal').modal('show');
    $('#detailsContent').html('<p class="text-center"><i class="fa fa-spinner fa-spin"></i> Loading...</p>');
    
    // Find the row data
    <?php foreach ($crud_history as $row): ?>
    if(id == <?php echo $row->id; ?>) {
        var html = '<table class="table table-bordered">';
        html += '<tr><th width="30%">Table Name</th><td><?php echo $row->table_name; ?></td></tr>';
        html += '<tr><th>Controller Name</th><td><?php echo $row->controller_name; ?></td></tr>';
        html += '<tr><th>Model Name</th><td><?php echo $row->model_name; ?></td></tr>';
        html += '<tr><th>View Directory</th><td><code><?php echo str_replace('\\', '\\\\', $row->view_directory); ?></code></td></tr>';
        html += '<tr><th>Controller Path</th><td><code><?php echo str_replace('\\', '\\\\', APPPATH . "controllers" . DIRECTORY_SEPARATOR . $row->controller_name . ".php"); ?></code></td></tr>';
        html += '<tr><th>Model Path</th><td><code><?php echo str_replace('\\', '\\\\', APPPATH . "models" . DIRECTORY_SEPARATOR . $row->model_name . ".php"); ?></code></td></tr>';
        html += '<tr><th>List View</th><td><code><?php echo str_replace('\\', '\\\\', $row->view_directory . DIRECTORY_SEPARATOR . 'list.php'); ?></code></td></tr>';
        html += '<tr><th>Form View</th><td><code><?php echo str_replace('\\', '\\\\', $row->view_directory . DIRECTORY_SEPARATOR . 'form.php'); ?></code></td></tr>';
        html += '<tr><th>Generated Date</th><td><?php echo date('d F Y, H:i:s', strtotime($row->generated_at)); ?></td></tr>';
        html += '<tr><th>Generated By</th><td><?php echo $row->generated_by_name; ?></td></tr>';
        html += '</table>';
        $('#detailsContent').html(html);
    }
    <?php endforeach; ?>
}

function deleteHistory(url) {
    Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this! Files will NOT be deleted, only history record.",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#6c757d',
        confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = url;
        }
    })
}
</script>
